#import "tab1Controller.h"
#import "CustomUI_acController.h"
@implementation tab1Controller
@synthesize currentContainer=_currentContainer;
@synthesize main_title=_main_title;
@synthesize main_next=_main_next;
@synthesize main_customer=_main_customer;
@synthesize main_product=_main_product;
@synthesize main_order=_main_order;
@synthesize main_action=_main_action;
@synthesize main_contract=_main_contract;
@synthesize main_work=_main_work;
@synthesize main_lines=_main_lines;
@synthesize main_chance=_main_chance;
@synthesize main_knowdge=_main_knowdge;
static NSString* baseHtmlResourcePath=@"Web/Html";
static UMWebViewBase* webView;
- (void)loadView
{
[super loadView];
}
- (void)viewDidLoad
{
[super viewDidLoad];
AppDelegate* appDelegate = [[UIApplication sharedApplication] delegate];
_currentContainer=[appDelegate currentContainer];
[_currentContainer initController:@"CustomerWindowModel"];
[_currentContainer initController:@"CustomerContentController"];
[_currentContainer initController:@"CustomerContentControllerEx"];
self.view=[[UMPLayoutView alloc] initWithLayoutType:Layout_vbox];
self.view.backgroundColor = [UIColor colorWithRed:0.8666667 green:0.8666667 blue:0.8666667 alpha:1];
CGFloat tab1width=0;
CGFloat tab1height=0;
tab1width = [[UIScreen mainScreen] applicationFrame].size.width;
tab1height = [[UIScreen mainScreen] applicationFrame].size.height-49;
self.view.frame = CGRectMake(0, 0, tab1width,tab1height);
UMPLayoutView*main=[[UMPLayoutView alloc] initWithLayoutType:Layout_vbox];
CGFloat mainwidth;
CGFloat mainheight;
mainwidth = self.view.frame.size.width;
mainheight = 0;
main.frame = CGRectMake(0,0,mainwidth,mainheight);
main.weightUMPView = 1;
main.paddingLeftUMP = 0;
main.paddingTopUMP = 0;
main.paddingRightUMP = 0;
main.paddingBottomUMP = 0;
main.backgroundColor = [UIColor clearColor];
[(UMPLayoutView*)self.view addLayoutSubView:main];
UMPLayoutView*main_head=[[UMPLayoutView alloc] initWithLayoutType:Layout_hbox];
CGFloat main_headwidth;
CGFloat main_headheight;
main_headwidth = main.frame.size.width;
main_headheight = 55;
main_head.frame = CGRectMake(0,0,main_headwidth,main_headheight);
main_head.weightUMPView = 0;
main_head.paddingLeftUMP = 0;
main_head.paddingTopUMP = 0;
main_head.paddingRightUMP = 0;
main_head.paddingBottomUMP = 0;
[main_head setBackgroundImageWithPathForUMP:@"nav"];
[(UMPLayoutView*)main addLayoutSubView:main_head];
UMPLayoutView*main_content=[[UMPLayoutView alloc] initWithLayoutType:Layout_vbox];
CGFloat main_contentwidth;
CGFloat main_contentheight;
main_contentwidth = 300;
main_contentheight = 324;
main_content.frame = CGRectMake(0,0,main_contentwidth,main_contentheight);
main_content.weightUMPView = 0;
main_content.paddingLeftUMP = 0;
main_content.paddingTopUMP = 0;
main_content.paddingRightUMP = 0;
main_content.paddingBottomUMP = 0;
main_content.alignUMP = 2;
main_content.backgroundColor = [UIColor clearColor];
[(UMPLayoutView*)main addLayoutSubView:main_content];
_main_title= [[UMPLabel alloc] initDefault];
CGFloat _main_titlewidth;
CGFloat _main_titleheight;
_main_titlewidth = 0;
_main_titleheight = main_head.frame.size.height;
_main_title.frame = CGRectMake(0,0,_main_titlewidth,_main_titleheight);
_main_title.weightUMPView = 1;
_main_title.paddingLeftUMP = 5;
_main_title.paddingTopUMP = 0;
_main_title.paddingRightUMP = 0;
_main_title.paddingBottomUMP = 0;
_main_title.alignUMP = 2;
_main_title.title = @"客户关系管理";
_main_title.textAlignment = UITextAlignmentCenter;
_main_title.textColor = [UIColor colorWithRed:1.0 green:1.0 blue:1.0 alpha:1];
_main_title.font = [UIFont systemFontOfSize:22];
_main_title.backgroundColor = [UIColor clearColor];
[(UMPLayoutView*)main_head addLayoutSubView:_main_title];
_main_next= [[UMPButton alloc] initDefault];
CGFloat _main_nextwidth;
CGFloat _main_nextheight;
_main_nextwidth = 50;
_main_nextheight = 45;
_main_next.frame = CGRectMake(0,0,_main_nextwidth,_main_nextheight);
_main_next.weightUMPView = 0;
_main_next.paddingLeftUMP = 0;
_main_next.paddingTopUMP = 0;
_main_next.paddingRightUMP = 0;
_main_next.paddingBottomUMP = 0;
_main_next.alignUMP = 2;
[_main_next setBackgroundImgFromPath:@"plus" forState:UMP_Controls_State_Normal];
[_main_next setImgFromPath:@"plus" forState:UMP_Controls_State_Normal];
[_main_next addTarget:self action:@selector(nextPage) forControlEvents:UIControlEventTouchUpInside];
[(UMPLayoutView*)main_head addLayoutSubView:_main_next];
UMPLayoutView*row1=[[UMPLayoutView alloc] initWithLayoutType:Layout_hbox];
CGFloat row1width;
CGFloat row1height;
row1width = 300;
row1height = 108;
row1.frame = CGRectMake(0,0,row1width,row1height);
row1.weightUMPView = 0;
row1.paddingLeftUMP = 0;
row1.paddingTopUMP = 0;
row1.paddingRightUMP = 0;
row1.paddingBottomUMP = 0;
row1.alignUMP = 2;
row1.backgroundColor = [UIColor clearColor];
[(UMPLayoutView*)main_content addLayoutSubView:row1];
UMPLayoutView*row2=[[UMPLayoutView alloc] initWithLayoutType:Layout_hbox];
CGFloat row2width;
CGFloat row2height;
row2width = 300;
row2height = 108;
row2.frame = CGRectMake(0,0,row2width,row2height);
row2.weightUMPView = 0;
row2.paddingLeftUMP = 0;
row2.paddingTopUMP = 0;
row2.paddingRightUMP = 0;
row2.paddingBottomUMP = 0;
row2.alignUMP = 2;
row2.backgroundColor = [UIColor clearColor];
[(UMPLayoutView*)main_content addLayoutSubView:row2];
UMPLayoutView*row3=[[UMPLayoutView alloc] initWithLayoutType:Layout_hbox];
CGFloat row3width;
CGFloat row3height;
row3width = 300;
row3height = 108;
row3.frame = CGRectMake(0,0,row3width,row3height);
row3.weightUMPView = 0;
row3.paddingLeftUMP = 0;
row3.paddingTopUMP = 0;
row3.paddingRightUMP = 0;
row3.paddingBottomUMP = 0;
row3.alignUMP = 2;
row3.backgroundColor = [UIColor clearColor];
[(UMPLayoutView*)main_content addLayoutSubView:row3];
_main_customer= [[UMPButton alloc] initDefault];
CGFloat _main_customerwidth;
CGFloat _main_customerheight;
_main_customerwidth = 100;
_main_customerheight = 108;
_main_customer.frame = CGRectMake(0,0,_main_customerwidth,_main_customerheight);
_main_customer.weightUMPView = 0;
_main_customer.paddingLeftUMP = 0;
_main_customer.paddingTopUMP = 0;
_main_customer.paddingRightUMP = 0;
_main_customer.paddingBottomUMP = 0;
[_main_customer setBackgroundImgFromPath:@"w1" forState:UMP_Controls_State_Normal];
[_main_customer setImgFromPath:@"w1" forState:UMP_Controls_State_Normal];
[_main_customer addTarget:self action:@selector(nextPage) forControlEvents:UIControlEventTouchUpInside];
[(UMPLayoutView*)row1 addLayoutSubView:_main_customer];
_main_product= [[UMPButton alloc] initDefault];
CGFloat _main_productwidth;
CGFloat _main_productheight;
_main_productwidth = 100;
_main_productheight = 108;
_main_product.frame = CGRectMake(0,0,_main_productwidth,_main_productheight);
_main_product.weightUMPView = 0;
_main_product.paddingLeftUMP = 0;
_main_product.paddingTopUMP = 0;
_main_product.paddingRightUMP = 0;
_main_product.paddingBottomUMP = 0;
[_main_product setBackgroundImgFromPath:@"w2" forState:UMP_Controls_State_Normal];
[_main_product setImgFromPath:@"w2" forState:UMP_Controls_State_Normal];
[(UMPLayoutView*)row1 addLayoutSubView:_main_product];
_main_order= [[UMPButton alloc] initDefault];
CGFloat _main_orderwidth;
CGFloat _main_orderheight;
_main_orderwidth = 100;
_main_orderheight = 108;
_main_order.frame = CGRectMake(0,0,_main_orderwidth,_main_orderheight);
_main_order.weightUMPView = 0;
_main_order.paddingLeftUMP = 0;
_main_order.paddingTopUMP = 0;
_main_order.paddingRightUMP = 0;
_main_order.paddingBottomUMP = 0;
[_main_order setBackgroundImgFromPath:@"w3" forState:UMP_Controls_State_Normal];
[_main_order setImgFromPath:@"w3" forState:UMP_Controls_State_Normal];
[(UMPLayoutView*)row1 addLayoutSubView:_main_order];
_main_action= [[UMPButton alloc] initDefault];
CGFloat _main_actionwidth;
CGFloat _main_actionheight;
_main_actionwidth = 100;
_main_actionheight = 108;
_main_action.frame = CGRectMake(0,0,_main_actionwidth,_main_actionheight);
_main_action.weightUMPView = 0;
_main_action.paddingLeftUMP = 0;
_main_action.paddingTopUMP = 0;
_main_action.paddingRightUMP = 0;
_main_action.paddingBottomUMP = 0;
[_main_action setBackgroundImgFromPath:@"w4" forState:UMP_Controls_State_Normal];
[_main_action setImgFromPath:@"w4" forState:UMP_Controls_State_Normal];
[(UMPLayoutView*)row2 addLayoutSubView:_main_action];
_main_contract= [[UMPButton alloc] initDefault];
CGFloat _main_contractwidth;
CGFloat _main_contractheight;
_main_contractwidth = 100;
_main_contractheight = 108;
_main_contract.frame = CGRectMake(0,0,_main_contractwidth,_main_contractheight);
_main_contract.weightUMPView = 0;
_main_contract.paddingLeftUMP = 0;
_main_contract.paddingTopUMP = 0;
_main_contract.paddingRightUMP = 0;
_main_contract.paddingBottomUMP = 0;
[_main_contract setBackgroundImgFromPath:@"w5" forState:UMP_Controls_State_Normal];
[_main_contract setImgFromPath:@"w5" forState:UMP_Controls_State_Normal];
[(UMPLayoutView*)row2 addLayoutSubView:_main_contract];
_main_work= [[UMPButton alloc] initDefault];
CGFloat _main_workwidth;
CGFloat _main_workheight;
_main_workwidth = 100;
_main_workheight = 108;
_main_work.frame = CGRectMake(0,0,_main_workwidth,_main_workheight);
_main_work.weightUMPView = 0;
_main_work.paddingLeftUMP = 0;
_main_work.paddingTopUMP = 0;
_main_work.paddingRightUMP = 0;
_main_work.paddingBottomUMP = 0;
[_main_work setBackgroundImgFromPath:@"w6" forState:UMP_Controls_State_Normal];
[_main_work setImgFromPath:@"w6" forState:UMP_Controls_State_Normal];
[(UMPLayoutView*)row2 addLayoutSubView:_main_work];
_main_lines= [[UMPButton alloc] initDefault];
CGFloat _main_lineswidth;
CGFloat _main_linesheight;
_main_lineswidth = 100;
_main_linesheight = 108;
_main_lines.frame = CGRectMake(0,0,_main_lineswidth,_main_linesheight);
_main_lines.weightUMPView = 0;
_main_lines.paddingLeftUMP = 0;
_main_lines.paddingTopUMP = 0;
_main_lines.paddingRightUMP = 0;
_main_lines.paddingBottomUMP = 0;
[_main_lines setBackgroundImgFromPath:@"w7" forState:UMP_Controls_State_Normal];
[_main_lines setImgFromPath:@"w7" forState:UMP_Controls_State_Normal];
[(UMPLayoutView*)row3 addLayoutSubView:_main_lines];
_main_chance= [[UMPButton alloc] initDefault];
CGFloat _main_chancewidth;
CGFloat _main_chanceheight;
_main_chancewidth = 100;
_main_chanceheight = 108;
_main_chance.frame = CGRectMake(0,0,_main_chancewidth,_main_chanceheight);
_main_chance.weightUMPView = 0;
_main_chance.paddingLeftUMP = 0;
_main_chance.paddingTopUMP = 0;
_main_chance.paddingRightUMP = 0;
_main_chance.paddingBottomUMP = 0;
[_main_chance setBackgroundImgFromPath:@"w8" forState:UMP_Controls_State_Normal];
[_main_chance setImgFromPath:@"w8" forState:UMP_Controls_State_Normal];
[(UMPLayoutView*)row3 addLayoutSubView:_main_chance];
_main_knowdge= [[UMPButton alloc] initDefault];
CGFloat _main_knowdgewidth;
CGFloat _main_knowdgeheight;
_main_knowdgewidth = 100;
_main_knowdgeheight = 108;
_main_knowdge.frame = CGRectMake(0,0,_main_knowdgewidth,_main_knowdgeheight);
_main_knowdge.weightUMPView = 0;
_main_knowdge.paddingLeftUMP = 0;
_main_knowdge.paddingTopUMP = 0;
_main_knowdge.paddingRightUMP = 0;
_main_knowdge.paddingBottomUMP = 0;
[_main_knowdge setBackgroundImgFromPath:@"w9" forState:UMP_Controls_State_Normal];
[_main_knowdge setImgFromPath:@"w9" forState:UMP_Controls_State_Normal];
[(UMPLayoutView*)row3 addLayoutSubView:_main_knowdge];
}
- (void)viewWillAppear:(BOOL)animated
{
[SysContext getInstance].CurrentViewController = self;
[super viewWillAppear:animated];
}
- (void)viewDidUnload
{
[super viewDidUnload];
}
- (void)dispacherEventToWeView:(NSString*)params
{
[webView.m_jsBridge callHandler:@"eventdispacher" data:params];
[_currentContainer DataBinding:self jsonData:params];
}
- (IBAction)nextPage{
CustomUI_acController* next = [[CustomUI_acController alloc] initWithNibName:nil bundle:nil];
[self.view addSubview:next.view];
}
- (IBAction)Close{
[self.view removeFromSuperview];
}
- (IBAction)Ok{
}
@end
